### ISSUE TITLE
All components context config

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#123]
## Gist

The idea is to provide default for selected prop for all components.
This is not as useful in framework, but there are plenty of external uses (i.e. in example we're defining guest user for components that might require it).

## Syntax example

```js
Vue.use(ContextPlugin, {
  all: {
    user: {name: 'John Doe', type: 'guest'}
  }
})
```

**Comment by Derranion** [comment]
It is almost ready. (local branch)

I just need to add documentation for this feature, will add pull request tomorrow.

**Comment by Derranion** [comment]
As discussed moving this setting to `globalConfig` -> `componentAll`.

Also I've decided to refactor `withConfigTransport` and some of it's imports while doing this issue because it seems to have a lot of room for improvement in terms of efficiency and readability.

Hopefully I will remove ~50+ lines of code and make it a lot faster, easier to read.
