### ISSUE TITLE
Badge component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#18]
# Docs

- [x] Do after [docs boilerplate](#17) is done.

# Props
- [x] `transparent: Boolean`
- [x] `multiLine: Boolean`
- [x] `label: [String, Number]`
- [x] `bottom: Boolean`
- [x] `left: Boolean`
- [x] `overlap: Boolean`
- [x] `color: String` - use theme plugin
- [x] `textColor: String` - use theme plugin
- [x] `dot: boolean`
- [x] `visibleEmpty: boolean` - should show badge when no value is passed (default behaviour is hide).

# Design
- [x] Transition on change (on value change, on disappearing, changing to dot etc.
- [x] Present to @xx13 after finishing.

# Notes
- [x] Native events are to be propagated
- [x] content could be passed via slot or via `label` prop. Slot has priority if both are declared.
- [x] Badge should be visible when no value is passed.
- [x] Should allow to be used on same level as text goes (see quasar ref). Add needed prop to issue and component.

# Refs
* [Quasar](https://quasar.dev/vue-components/badge)
* [Vuetify](https://vuetifyjs.com/en/components/badges)
* [Ant-design](https://ant.design/components/badge/)

# Author
* @asvae

**Comment by asvae** [comment]
@Kreezag please don't move anything from Backlog to New issues.
Backlog is ready for implementation issues (past research process), New issues are not.

**Comment by xx13** [comment]
@Kreezag @asvae it looks good!
1. I'd rather have 'Danger' as a default badge value rather than Primary Green.
2. Can we have 'Dot' style totally round — right now it looks like a square with rounded corners.
3. Outline style has issues with all colors except for the primary one when text color changes from white to green, but all other text notifications remain white.
4. Slider control has a bug — its pin is stuck on the left.

Meanwhile I'm preparing the way we can present this component.

**Comment by Kreezag** [comment]
> @Kreezag @asvae it looks good!
> 
> 1. I'd rather have 'Danger' as a default badge value rather than Primary Green.
> 2. Can we have 'Dot' style totally round — right now it looks like a square with rounded corners.
> 3. Outline style has issues with all colors except for the primary one when text color changes from white to green, but all other text notifications remain white.
> 4. Slider control has a bug — its pin is stuck on the left.
> 
> Meanwhile I'm preparing the way we can present this component.
Outline badges its removed.
All fixed
