### ISSUE TITLE
[Packages/nuxt] TS Errors in IDE in development 

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1821]
**Vuestic-ui version:** 1.4.0-alpha6
<img width="561" alt="image" src="https://user-images.githubusercontent.com/55198465/169485963-ed55ce69-e08f-473e-9bc8-bb81adebf4f8.png">

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/55198465/169486220-3756772a-b86e-4ede-8a68-e9e8ede322a3.png">

**Comment by aluarius** [comment]
The first. `npm i` at `packages/nuxt` solves this problem :) useToast export was added recently to Vuestic UI.

The second. `.nuxt/tsconfig.json` file generated via `npm run dev:prepare`. `packages/nuxt/tsconfig.js` with `extends` was generated at the beginning by `@nuxt/kit`.

Think, can close this issue.

**Comment by m0ksem** [comment]
> The first. `npm i`/`yarn install` at `packages/nuxt` solves this problem (it was same for me) :) useToast export was added recently to Vuestic UI.
> 
> The second. `.nuxt/tsconfig.json` file generated via `npm run dev:prepare`. `packages/nuxt/tsconfig.js` with `extends` was generated at the beginning by `@nuxt/kit`.
> 
> Think, can close this issue.

Would be cool if ts path will point to pacakges/ui/src/main.ts

Tried myself on it, and it doesn't work, some reason.  It uses latest vuestic-ui version from it's own node_modules, because of pacakge.json. It is correct behavior, 

We can safety ignore these errors for now, but in future will be nice to remove them.
