### ISSUE TITLE
Use names in align type instead of string

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1884]
![image](https://user-images.githubusercontent.com/23530004/171155590-a03aac37-7df9-4b3a-9952-71c0a99baa77.png)

```ts
const horizMap = {
  left: 'flex-start',
  center: 'center',
  right: 'flex-end',
  between: 'space-between',
  around: 'space-around',
}
```

use keyof typeof horizMap instead of string

/home/m0ksem/projects/vuestic-ui/packages/ui/src/composables/useAlign.ts

**Comment by dnischeta** [comment]
Hello, @m0ksem !

It isn't so trivial, because `align` prop is used for both `justifyContent` and `alignItems` calculation (see https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/composables/useAlign.ts#L46).

That's why we cant just use `keyof typeof horizMap`, at least we should use `keyof typeof horizMap | keyof typeof vertMap`, that solution would work for all appropriate align values. But there is still some limitations/impurity due to single prop usage for both justify and align.

Could you please share your thoughts about that?

**Comment by m0ksem** [comment]
Anyway, isn't align prop shouldn't be the same for vertical and horizontal?

**Comment by rustem-nasyrov** [comment]
@m0ksem, looks like it is fixed by https://github.com/epicmaxco/vuestic-ui/pull/2777 and https://github.com/epicmaxco/vuestic-ui/pull/2804.
