### ISSUE TITLE
Modal on Mobile

### ISSUE THREAD

**Issue by goldbergmoshe** [epicmaxco/vuestic-ui#1929]
**Vuestic-ui version:** 1.4.1

**Steps to reproduce**

If you open any of the Modal sizes on a mobile device, the modal takes up the entire screen. 
I would love to start using this ui framework, could this be fixed? It is literally as easy as adding media queries to the css. 
Could you fix this?
Would you accept a PR for this?

Best Regards

**Comment by m0ksem** [comment]
I think this bug is a feature nobody asked for. 

Modal become full screen on mobile. We need to add `fullscreen-on-mobile` prop with default false, so somebody who need fullscreen modals on mobile can set it with GlobalConfig.

Any PRs are welcome. We will help with conflicts or help if you stack.

Would you like to fix it? Or you can wait until somebody will take this task.

**Comment by asvae** [comment]
Agreed.
Checked some refs - and other frameworks don't go fullscreen on mobile, so neither should we.

**Comment by m0ksem** [comment]
This is already implemented, actually. 
https://vuestic.dev/en/ui-elements/modal#full-screen

User can turn off this feature `mobile-fullscreen` as `false` to component or change it in global config

```ts
createVuestic({
   config: {
      components: {
         VaModal: {
             mobileFullscreen: false.
         }
      }
   }
})
```
