### ISSUE TITLE
VaCounter : Component is missing template or render function.

### ISSUE THREAD

**Issue by munavi** [epicmaxco/vuestic-ui#1930]
**Vuestic-ui version:** 1.4.1
"vue-cli-plugin-vuestic-ui": "~1.0.6"
"vite": "^2.9.5"

**Steps to reproduce**
I'm using the version **Vue 3.2.33**

**What is the expected behavior?**
The Component "va-counter"should be visible. I dont't have any errors in IDE

**What is the current behavior?**
VaCounter : Component is missing template or render function.
It does not work when va-counter is in a separate .vue file and imported as a component.

```
<template>
  <div>
    <va-counter
        v-model="props.counter"
        manual-input
        messages="Manual-input"
    />
  </div>
</template>
```

```
[Vue warn]: Component is missing template or render function. 
   at <Counter counter=10 > 
   at <VaListItem class="list-item" > 
   at <ListItem label="Nudeln" counter=10 > 
   at <VaListItem key=0 class="list-item" > 
   at <VaList> 
   at <List> 
   at <VaContent> 
   at <ListPage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
   at <RouterView> 
   at <App>
```

Вo you have any advice on how to fix this? Thank you in advance
**Other information**

**Comment by Derranion** [comment]
Hello hello @munavi 

We resolved [similar Va-checkbox issue](https://github.com/epicmaxco/vuestic-ui/issues/1631) by this [pull request (Remove withTransportConfig wrapper)](https://github.com/epicmaxco/vuestic-ui/pull/1634) already.

Are you sure that you are using last Vuestic version(`1.4.1` currently)?

Because I was not able to reproduce it.

If you have used the same version could you please send your `main.js`

Thanks.

**Comment by m0ksem** [comment]
Closing due inactivity.
