### ISSUE TITLE
`VaSlider`: whether `range` mode is redundant?

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1961]
Now we have `range` prop:
  - `range` = false
`<va-slider v-model="value" /> // value: 45`

  - `range` = true
`<va-slider v-model="value" range /> // value: [45, 65]`

Proposal:

`<va-slider v-model="value" /> // value: 45 --> single`
`<va-slider v-model="value" /> // value: [45, 65] --> range`

**Comment by asvae** [comment]
At max - we can add warning for slider in this case. But probably not our problem.

**Comment by arkmadj** [comment]
@m0ksem Can I have a go at this issue?

**Comment by asvae** [comment]
@arkmadj sorry for screw up from our side (considering this issue ready for implementation), but this won't work. :<

The problem is mixing model change with logic.
We conventionally do this as there might be a case where backend returns `null` or `any[]`. And `null` would force slider to become single mode, which is completely wrong and confusing.
