### ISSUE TITLE
How to use data table as server side

### ISSUE THREAD

**Issue by kamleshdarteweb** [epicmaxco/vuestic-ui#2118]
**Vuestic-ui version:** 1.4.6

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

**Comment by m0ksem** [comment]
Hey. Can you explain a bit what issue have you faced?

**Comment by AntoineBarroux** [comment]
Hi guys ! I have exactly the same question. I've an API that returns paginated data, and would like to use it to fill a data-table with a pagination component.
The problem is, when page is updated from va-pagination, i'm fetching my api with the current page element, so it returns for example 20 items. But as my data-table is now on page 2, it does not display any element because my items list has only 20 elements. How to manage server-side pagination with data-table ? I can't see anything about it in the documentation ! 
Thanks a lot and great job for this library
