### ISSUE TITLE
Roadmap mobile version is not awesome

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2183]
**Vuestic-ui version:** 1.4.8

<img width="436" alt="image" src="https://user-images.githubusercontent.com/5394573/181859212-deb8a6d0-3cb8-4d70-a6a7-e9c7669d6b99.png">

**Comment by ameer-khan-ashraf** [comment]
Hi I would like to work on this. Is there a contributing guide?

**Comment by m0ksem** [comment]
> Hi I would like to work on this. Is there a contributing guide?

Hey. We have a few guides here: https://vuestic.dev/en/contribution/documentation-page

We want to smoothly move our docs to tailwind and would be nice if this layout issue will be fixed with tailwind. But we have not installed and adopted docs for tailwind yet. If you're here for long, it would be nice if you can integrate tailwind and solve this issue with it. But, anyway, any fix will be appreciated. I assume tailwind integration can take a bit more of time.

FYI, you'll need to work with `packages/docs/src/page-configs/introduction/roadmap/components/roadmap.vue`.

**Comment by ameer-khan-ashraf** [comment]
Hi, I created a pull request with the fix. please have a look and let me know if the process is okay so that I can start working on integrating tailwind.
