### ISSUE TITLE
`VaSelect` tagging state feature

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2243]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/64714442/184590724-24d50c6b-e836-4087-a231-9bd4cdad39ea.png">

Ref: https://vue-multiselect.js.org/

**Comment by asvae** [comment]
We have something similar, but 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/5394573/185364604-b3e3ed9d-5035-4ce2-8348-3cc5020c9376.png">

Needs research.

* Not sure if we want to use separate component or the same one?
- [ ] Maybe we can also set default values for docs examples, so that tags are visible for users.

**Comment by aluarius** [comment]
All other frameworks (vuetify, quasar, mui, ant) are simply using chips inside select components for this purpose. So, i will just update our documentation to highlight this feature.
