### ISSUE TITLE
VaImage improvements

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2537]
Right now image component is not on point in a number of ways:
* offers very little functionality
* is not designed to work with SSR (right now error/loading demos do not work properly. loading - works only for image updates, error - works only for non ssr), the issue is that when image or its wrapper is `display: none` - browser doesn't load image, so `onload` and `onerror` triggers do not happen.
- [ ] return (currently excluded because of known hydration issue) va-image component to the test flow after rework (https://github.com/epicmaxco/vuestic-ui/pull/2651).

We have to improve that.

I would suggest another round of investigation + implemetation with full rework.

We can take inspiration to [Quasar implementation](https://github.com/quasarframework/quasar/blob/dev/ui/src/components/img/QImg.js) as it's conceptually close to what we're doing.

**Comment by aluarius** [comment]
During this component rework i suggest the following changes:

* Add built-in zoom behaviour (https://ant.design/~demos/components-image-demo-basic). Do we need this? Own implementation or side package? Enable boolean props or make it enabled by default and  add disable-preview prop? Also i'm not sure if we need controls for the zoomed image (in case of our implementation), but Ant Design and Naive Ui have it;

<img width="832" alt="image" src="https://user-images.githubusercontent.com/64714442/210035572-e73e37cd-9604-48b7-a36f-ab33e7d0c1d6.png">

* Error-loading fallback (text or image, may be implement as composable and reuse Rustem's idea https://github.com/epicmaxco/vuestic-ui/issues/2663). Fallback textual prop;
* Add progressive loading boolean prop (https://ant.design/~demos/components-image-demo-placeholder). Can't realize the value of this feature, but it's pretty modern;
* Lazy load boolean (imo very usefull). Load image only when it becomes visible;
* Max-width & max-height props (check if components wrapper style will be enough for this, if not - let's implement);
* Fixed wrapper size with contain-image state (also very useful for grid with fixed images):

<img width="937" alt="image" src="https://user-images.githubusercontent.com/64714442/210035891-66065db7-4f91-4be1-960a-94783cf0e393.png">

* Aspect ratio - we already have it, but may be we want to move it to the different component because of https://github.com/epicmaxco/vuestic-ui/issues/2227 ?
* Gradient overlay (https://vuetifyjs.com/en/components/images/#gradients). Or leave it for the default slot?
* Change `contain` boolean prop to `fit` prop with all object fit options.
* Placeholder fallback. But may be better to leave it for the slot too.
* Scrset support (https://quasar.dev/vue-components/img#responsive).
* `draggable` default `true` prop (mostly for internal use) change to `not-draggable` just in purpose of more convenient use.
* Add `title` prop to proxy title value. Rarely, but is still used.

Slots:
* Add placeholder slot. Leave the rest with no changes.
