### ISSUE TITLE
Button plain preset set color to transparent, so svg can not be visible

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2564]
![image](https://user-images.githubusercontent.com/23530004/197694983-8fb75e9e-053b-424f-9bcf-616d5a6f07d3.png)

Set docs navigation button to plain preset and icon becomes invisible.

(if you want to do this task - consult @aluarius or @m0ksem first to get an idea)

**Comment by m0ksem** [comment]
@aluarius, It is not a fix for this issue. For now, SVG doesn't react on VaButton text color because of filter thing we use. It wight worth it to have color instead, to prevent this kind of bugs.

**Comment by aluarius** [comment]
@m0ksem no, it is. I've tested icons (passed in via prop) with buttons - everything works fine for all presets. The reason why here was a bug - because custom broken svg was passed via icon slot. Icon's slot scope, if needed, provides color variable, that relies on current button content color. So, can't see any problem here, but if i'm not right, can discuss it in slack.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/64714442/206784276-c9c0526c-5230-4f94-8053-75296681bbdc.png">
