### ISSUE TITLE
All CSS always import in Nuxt 3

### ISSUE THREAD

**Issue by azoom-nguyen-van-nam** [epicmaxco/vuestic-ui#2839]
**Vuestic-ui version:** 1.5.3 and **@vuestic/nuxt:** 1.0.9

I used Vuestic with `Nuxt 3` and config as below:

![image](https://user-images.githubusercontent.com/101168054/210527692-53b0cae8-b603-465b-bf10-4765297f3f5a.png)
![image](https://user-images.githubusercontent.com/101168054/210527141-30a98f38-0066-4060-85e9-585888eee5fb.png)

But in the head tag of HTML document, even though I only use 1 button on each page, I always see all the CSS being imported.
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/101168054/210528297-1b10f575-6344-4bce-b786-7b96c824b61b.png">

and the CSS maybe duplicated: ⬇️ 
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/101168054/210530874-e48dc3ef-3292-4f40-8f58-e41312155386.png">

If it was built for Production ENV, would it still be that way?
**_Please help me explain or point out the error?_**

**Comment by m0ksem** [comment]
Hey, @azoom-nguyen-van-nam. Please use `@vuestic/nuxt` following guide below:

https://vuestic.dev/en/getting-started/nuxt#installation

`nuxtApp.vueApp.use(createVuestic())` is an incorrect way to register vuestic plugin, because nuxt will not tree-shake anything.

With  `@vuestic/nuxt` you don't need to import `vuestic-ui` at all.

If you still have some questions, feel free to ask for help in [Discord](https://discord.gg/u7fQdqQt8c).

**Comment by azoom-nguyen-van-nam** [comment]
@m0ksem oh sorry. It did't work!
![image](https://user-images.githubusercontent.com/101168054/210681910-b84ce532-9323-4a78-aa48-34398acd6659.png)

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/101168054/210682421-740695f0-8f4c-402f-81f2-a03f72161e9b.png">

Although it appears to have lost one import, all of the CSS is still imported into the head tag.

**Comment by m0ksem** [comment]
Thanks, @azoom-nguyen-van-nam. Can confirm this issue is related to `@vuestic/nuxt` package when all CSS set to true.

You can prevent all CSS to be registered for now by manually defining which CSS modules you want to use:
```ts
  vuestic: {
    // ...
    css: ['grid', 'reset', 'typography'],
  },
```

**Comment by azoom-nguyen-van-nam** [comment]
@m0ksem Thanks for your help

>  vuestic: {
    // ...
    css: ['grid', 'reset', 'typography'],
  },
 
I attempted the partial import, however the issue is still present (even I set css: false).

**Comment by m0ksem** [comment]
> @m0ksem Thanks for your assistance
> 
> > vuestic: {
> > // ...
> > css: ['grid', 'reset', 'typography'],
> > },
> 
> I attempted the partial import ⬆️ , however the issue is still present (even I set `css: false`).

Did you check this in production build or dev? Just a reminder that tree-shaking works only in production build. E.g. there is not tree-shaking in `npm run dev`. Also, we do need a small amount of CSS even if there are no components used, so it is OK to have a bit of it. We provide composables, like useToast, or useModal, which use components. This is why you can face some additional css, because VaModal and VaToast always registered by nuxt.

**Comment by azoom-nguyen-van-nam** [comment]
@m0ksem thank you, everything was clear. I tried build and it worked.

**Comment by azoom-nguyen-van-nam** [comment]
@m0ksem 
I'll solve this issue in my project in the short term like way.
```
export default defineNuxtConfig({
  css: ['vuestic-ui/dist/styles/index.css'],
  modules: ['@vuestic/nuxt'],
  vuestic: {
    ....
    css: false
  }
})
```
I'm hoping we can merge above PR shortly.
Thanks
