### ISSUE TITLE
VaButtonDropdown's size is bigger than VaButton's size.

### ISSUE THREAD

**Issue by Sadnessa** [epicmaxco/vuestic-ui#2922]
**Vuestic-ui version:** 
1.5.3

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/67637329/216949126-bf6f45cc-69d1-4b79-8eb6-aae413cbb819.png)

**Comment by m0ksem** [comment]
I have a little bit different issue, but I think it caused by the same problem

After new button design update icon cause button to be a slightly bigger. 
![image](https://user-images.githubusercontent.com/23530004/217077403-2bacfc79-1ed9-447e-8c39-e64f698e9670.png)


Pretty sure icons width and height must be 1em, so it is the same height as font.
