### ISSUE TITLE
Migrate Dropdown to floating-ui

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3083]
**Vuestic-ui version:** 1.6.1

**Steps to reproduce**
Reduce browser height => click on colors dropdown

**What is the expected behavior?**
at least scroll for colors list 

**What is the current behavior?**

https://user-images.githubusercontent.com/45711229/221502156-f091fffb-27aa-43c0-806b-eb3065ac1c19.mov

**Comment by gweesin** [comment]
it's seems to be the content coords calculation error, and the `useDomRect` hook could't trigger when the document resized.

I can try to solve this bug, i'll modify the `useDropdown` hook and edit the Colors element maxHeight of docs page.

From a long-term perspective, floating-ui can handle this problem so elegant, maybe migrate the implementation to floating-ui is better choice.

**Comment by gweesin** [comment]
> > From a long-term perspective, floating-ui can handle this problem so elegant, maybe migrate the implementation to floating-ui is better choice.
> 
> Hello, @gweesin! Yes, we have plans to migrate it to the floating-ui. Don't mind if I assign to you this issue?

I'm glad to take over this issue. Thank you for giving me the opportunity to contribute to the project!

**Comment by m0ksem** [comment]
Hey, @gweesin. Should we consider this issue as migration to floating-ui or fixing the described bug?

If it is a migration to floating-ui make sure we're not importing their stuff related to platform (e.g. ReactNative). We have been using PoperJS until they renamed into floating-ui, and it has SSR issues at the very beginning, so this must be considered too. I hope all of this fixed in `@floating-ui/vue`. 

Good luck!

**Comment by gweesin** [comment]
Hello, @m0ksem . You're right, we need to approach this issue as a migration to floating-ui, which could potentially require a significant amount of modifications.

I apologize for overlooking the issue related to SSR previously, but I will make sure to thoroughly consider and test this problem now. 😂 Additionally, I also hope that the issues you mentioned have been fixed in `@floating-ui/vue`.

Thank you for your professionalism.

**Comment by asvae** [comment]
@gweesin hey, thanks for you interest :)

you can communicate with @m0ksem to make this a possibility, probably would be hard to manage some of the usecases on your own.

This issues is pretty important for us - it doesn't affect only this dropdown in docs, but rather all droopdowns.

🤗

**Comment by m0ksem** [comment]
This will probably fix:
#2904 
#3083

**Comment by m0ksem** [comment]
This will probably fix https://github.com/epicmaxco/vuestic-ui/issues/3458
