### ISSUE TITLE
Make landing page look excellent on loading

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3420]
**Vuestic-ui version:** 1.6.4

<img width="1246" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/66032416-b7b6-47c8-95c1-5ebf5f93d258">

Can we make this page look excellent (without white button on loading).

**Comment by m0ksem** [comment]
The screen shot in issue body is incorrect. We want to fix this lag at the begining:
![image](https://github.com/epicmaxco/vuestic-ui/assets/23530004/4de9b060-bae4-4f8a-98c4-880f9c28c2c2)

**Comment by m0ksem** [comment]
I think the issue here in fonts. So we need change this line:

<img width="944" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/ec933324-320b-4669-9ad7-fa71d852910d">

**Comment by m0ksem** [comment]
Font didn't helped. I'm not sure why we have this issue, because it is rendered correctly. Looks like something related to fonts...

**Comment by zvenigorodskaia** [comment]
still has problem with fonts and image

https://github.com/epicmaxco/vuestic-ui/assets/35342240/993d211d-e0c4-42cc-b0c9-67f81a8acbc3

**Comment by m0ksem** [comment]
Since we use custom fonts, we might make three things: 
- show default font and replace it when font is loaded
- hide default font (no text will be shown) until font is loaded
- make a loader (show nothing until page is loaded)

The most appropriate is to have default font and replace it with loaded font at first page load. 

To completely remove custom font loading, we can use default system font, but we need to clarify it with @xx13. 

We could also add a blank loader as we did for any docs page, but it will not look right and cause blink, because we have different colored backgrounds on landing page.

https://github.com/epicmaxco/vuestic-ui/assets/23530004/3cd9c74c-f3c6-4606-95e6-3b23aadf1010

The image is fixed here: https://github.com/epicmaxco/vuestic-ui/pull/3565
