### ISSUE TITLE
VaInput: Update input value when v-model is update

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3996]
Maybe we should do it inside VaInput. I feel like it is not obvious to user (and for the one who wrote this doc example too). I'd expect v-model to be the same as input.value. What do you think?

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/pull/3980#discussion_r1377000709_

---

Maybe it must be done in VaInputWrapper. Idea here is to sync value in input HTMLElement and v-model.

**Comment by speedpro** [comment]
Sorry to respond to a closed issue, but any chance we can make this optional? 

I have a use case where I'm using `:model-value` to provide the inital value for a 'search' box, then using `@update:model-value` to call an async debounced function that does it's thing, then sets the `:model-value` once the server call finishes. 

After updating to 1.8.6, I suddenly wasn't able to type smoothly into the input anymore because the textbox contents seemed to be locked to the `:model-value` prop (which was debounced)

**Comment by m0ksem** [comment]
@speedpro, can you please check if this issue is fixed in `vuestic-ui@0.0.0-experimental-72080bc8c-20231213`. And if you can, please, help me to understand issue better and make code example in https://ui.vuestic.dev/play. Thanks!

**Comment by speedpro** [comment]
Thanks @m0ksem, 

The experimental version didn't solve the issue. I rolled back to 1.8.5, and it seems to work as expected.

I've just tried the following code in the playground to demonstrate. If you quickly type in the textbox, you'll see that it only catches the last character or so. Maybe I'm misunderstanding something and this is the way vue's two-way binding is supposed to work.

```
<script setup>
  import { ref } from 'vue'

  const msg = ref('')
  const updateMessage = (val) => {
    setTimeout(() =>{
      //simulates async calls or debounced functions
      msg.value = val
    }, 200)
  }
</script>

<template>
  <h1 class="va-h1">{{ msg }}</h1>
  <VaInput :model-value="msg" @update:model-value="updateMessage" />
</template> 
```

**Comment by m0ksem** [comment]
@speedpro, I made same example in 1.8.4. Do you think it is correct behavior?
https://ui-experimental.vuestic.dev/play#eNp9Uclu2zAQ/ZUBL3YA24qbmyEbXZBDCnRBG/SkCyuNJaYSSXBI1YWgf++QspwFQU6S3rzRW2YQH6zd9AHFTuRUOmU9EPpgD4UGUJ01zsMADo8wwtGZDhZMXhQ6jkujyUNHNewjY7lYXD3CwVbS4xckkjUyYdnL9gr2BxgiB6LKverQBL9cRvwMA2QZqS60vEwg6Z8uoZRtS2AcVPjbBF1iBUd+eMVC8xa72LBCiFL8nOBxBe+ur5OpsdB5NgXkaPzhsbNRJAXNmy2UrSTaF6KX62ZbiMMwpGjjmGfNdmL9knfaBg+7zlTYrpMebzCtEPB+Svxi9qwGZmX8pzy7iINYianldSft5oGM5kukLorzgAqxm0tjdwHJq3IdVIQL0XhvaZdlQa3xZNFxpdrLNp408jYV9tm8w11nnVSaZQpxLmVkA574ZEdVv5AvTWdVi+6bnZp+aoMvYv5+Tph3AVczXjZY/nkFf6DT5Pe7Q0LXcxWXmZeuRj+Nb39+xRO/X4bcZmiZ/cbwB5JpQ/Q40T4GXbHtJ7zk9i61qXR9T7cnj5rmUNFoaiPxU8Wf3oj+aPdmc3NpcfwPZ64WNQ==

**Comment by speedpro** [comment]
Interesting. It was acting strange in 1.8.4, but when I increased the timeout to 500, it worked as expected.

When I increased the timeout in 1.8.6, it got stuck on only one character. 

Despite that, I'm starting to think 1.8.6 makes more sense because it's stricter two-way binding, and more predictable in the long run. Although I have a number of forms where I supply the :model-value, and use a debounced async function for the update, so maybe a "strict-binding" prop would be good cause then I can update the global config while I transition to the new approach.


The question I have is whether you can supply the model-value and still bind to the @change event rather than the @update:model-value event

**Comment by m0ksem** [comment]
> Interesting. It was acting strange in 1.8.4, but when I increased the timeout to 500, it worked as expected.
> 
> When I increased the timeout in 1.8.6, it got stuck on only one character. 
> 
> Despite that, I'm starting to think 1.8.6 makes more sense because it's stricter two-way binding, and more predictable in the long run. Although I have a number of forms where I supply the :model-value, and use a debounced async function for the update, so maybe a "strict-binding" prop would be good cause then I can update the global config while I transition to the new approach.
> 
> 
> The question I have is whether you can supply the model-value and still bind to the @change event rather than the @update:model-value event

Why would you need to denounce update the value?
