### ISSUE TITLE
Tree shaking (a la carte)

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#840]
See [vuetify tree shaking](https://vuetifyjs.com/en/features/treeshaking/). You can also check other frameworks.

What's we're trying to achieve:
* User should be able to load all framework in one go (full bundle).
* User should be able to load only parts of framework (partial bundle). We want to focus primarily on components (services can wait for now).

**Comment by smellyshovel** [comment]
@asvae 

That's what I've been able to come up with after doing some research. *Everything stated below is just how I understand it, so I may be wrong at some points.*

First of all, let's differentiate the concepts: **tree-shaking !== a-la-carte**.

# Tree-shaking
Tree-shaking is done on the *consuming* side. That's important. And it's only achievable when using ES2015 modules. That's even more important.

A user that consumes vuestic-ui in his project must set his build-tools in such a manner that when vuestic-ui is picked up by the bundler then all the exports provided by vuestic-ui which are not used in his project are not being included into his project's final build.

What must be done on our side to provide the tree-shaking support for vuestic-ui is the ES-modules build itself (vuestic-ui.esm.js or smtn like), which we currently don't provide as far as I can see.

**The caveat**: Webpack 4 doesn't support ES2015 modules whatsoever, Webpack 5 does, but solely as an experimental-feature. That means that we might end up using another bundler (Rollup would be a great choise IMHO) to provide the ESM build.

# A-la-carte

As I understand, it's a term introduced by the Vuetify-team to describe a possibility of achieving **tree-shaking-*like*** support for their lib.

How does it work. First of all, they generate (at least) 2 completely separate builds: the first one is the dist/ folder and the second one is the lib/ folder. While everything is pretty straightforward with the dist folder/, the lib/ folder in its turn is built in such a way that each component/mixin/whatever is bundled in its own file (preserving the project's folder-structure).

Then a user can import only those components/mixins/whatever that he's about to be using in his project.

And that (manually importing everything), as they (Vuetify) state on their site, can become a real hassle (for obvious reasons). That's why they introduced the webpack vuestic plugin (which is a part of the vue-cli vuestic plugin afaics) which implicitly adds needed imports (parsing templates for v-component-name usages?) when bundling the consumer-project.  And, of course, it doesn't work 100% of the time (take e.g. the `<component :is="v-button">` which must be handled manually). And, of course, it doesn't work beyond webpack. So if i'm building my vuetify-using-project with, for example, rollup then a-la-carte approach simply won't work at all (well, it will, but I will need to manually import everything).

**Why don't they use the "real" tree-shaking?**

I guess that's because they use old-tooling. And upgrading it might become a real pain.
To be more exact, they use Webpack 4 that doesn't support ES2015 modules whatsoever. Webpack 5 (which we're using) does, though it's still an experimental feature.

# So, what to do

If we want to implement the a-la-carte approach, we must configure the webpack the way that it outputs 2 separate bundles, write a similar to the Vuetify's one webpack-plugin and desirably provide a vue-cli-plugin which uses this webpack-plugin under the hood. There also might pop out issues with the global/per-component configuration.

If we decide to go the tree-shaking way, we should discuss the way we bundle our vuestic-ui as an ESM.

Need your comments, @asvae

**Comment by smellyshovel** [comment]
Useful link on the topic:

https://blog.theodo.com/2021/04/library-tree-shaking/
https://webpack.js.org/configuration/output/#module-definition-systems (particularly here: https://github.com/webpack/webpack/issues/2933#issuecomment-774253975)
