### ISSUE TITLE
Select issues

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#846]
- [x] Disabled select should not be focusable
![image](https://user-images.githubusercontent.com/5394573/121692322-aa0e3c00-cad0-11eb-8ebd-24300e994af2.png)

- [x] Remove outline from internal search, cursor should be the only indication of focus
![image](https://user-images.githubusercontent.com/5394573/121692378-b85c5800-cad0-11eb-94b9-4309f54fa3ea.png)

- [x] Navigating up from search should not close dropdown
- [x] Navigating up and down shouldn't unfocus search (use state to manage internal cursor, not focus).

**Comment by m0ksem** [comment]
I propose for this issue create a requirements list. Tho we can discuss how "Select" should be implemented correctly.

- [ ] For example, I agree that It will be better if you can open select with "Enter" and Close with "ESC" keyboard buttons instead of closing Select just scrolling up or down option list.

**Comment by Derranion** [comment]
Yeah, sounds nice to have - will do it as well,

I think it's a good idea to navigate only through items within the options list.

Especially if we will have "searchBar" active all the time.

Example:

1. Key UP will select 2rd item
2. Key DOWN will select 1st item
