### ISSUE TITLE
Datepicker component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#855]

**Comment by m0ksem** [comment]
# Date picker

## Summary
Datepicker component is form input, which accepts Date objects, Date objects array, or specific period as value.

I think we can make a date picker and time picker separately for the first release.

![image](https://user-images.githubusercontent.com/23530004/122749307-daef2d80-d295-11eb-9b2e-e7b833a7d605.png)

Design: https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=402%3A2

## Props

### Form props
- modelValue - Date | Date[] | { start: Date, end: Date }
- name - string (?)
- disabled - boolean
- readonly - boolean
- min / max - Im not sure we should use it, because we have allowedDates

### Date picker props
- valueType - 'single' | 'multiple' | 'range' | 'any'
- allowedDates - (d: Date) => boolean
- displayFormat - string | function - with function we can provide example of using https://date-fns.org/
- firstWeekDay - string
- weekDayNames - string[] - ['M', 'T', 'W', 'T', 'F', 'S', 'S']
- monthNames - string[] - ['JUN', 'FAB', ..., 'DEC']
- dayName - function - (d) =>  'prefix' + d
- currentDate - slightly outline current date  
  / or  
  showCurrentDate - we can use new Date()
- locale - (?) maybe on next, this way we can support non-gregorian calendars
- view - 'day' | 'month' | 'year' - current view or current picker (?)

### Dropdown
- isOpened - boolean

### Style
- color - default 'primary'
- weekendColor - default null - for example we can use 'danger' 
- prevMonthIcon
- nextMonthIcon
- hideWeekDays - or we can pass clear array to weekDayNames to hide it

## Emits
- update:modelValue
- update:day, update:month, update:year
- click, click:day, click:month, click:year
- hover, hover:day, hover:month, hover:year
- update:is-opened
- update:view

## Slots
...all slots from input  
...all slots from dropdown

## Methods
// I think we do not need it

**Comment by m0ksem** [comment]
Blocked by https://github.com/epicmaxco/vuestic-ui/issues/850

**Comment by asvae** [comment]
https://vcalendar.io/timezones.html - to refs :).
