### ISSUE TITLE
va-input-number

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-ui#9]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

It's will be nice to have input with numerical values controlled via controls or keyboard

**Suggested props**
- `max`, `min` -maximum and minimum values
- `step` - incremental step

**References**
[vue ant design](https://vue.ant.design/components/input-number/)
[element](https://element.eleme.io/#/en-US/component/input-number)

**Comment by asvae** [comment]
Issue needs more implementation details.
Also common case for number input from my experience is decimals. And these are actually instances of String, not Number! So that should be taken into consideration as well.

My recommendation is to use Cleave for this. As it's quite polished and powerful.

**Comment by igorprodev1** [comment]
As a result of the investigation, it turned out that a separate implementation of the input for entering a number is not needed. If you set type="number" for existing input, it behaves correctly, comparing with other frameworks and native number input.
After the investigation, I decided to close the ticket and create a new one for redesign with a low-priority.
<img width="472" alt="Screenshot 2020-09-29 at 19 56 26" src="https://user-images.githubusercontent.com/55927944/94589477-f8a2df80-028d-11eb-97c4-874d93b2eef9.png">
