### ISSUE TITLE
Update color docs

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#996]
* **What is the expected behavior?**
Checkbox color property should set color correctly.
* **What is the current behavior?**
For example color="purple" doesn't apply - Checkbox looks black
![CheckboxColorIssue](https://user-images.githubusercontent.com/7745899/128748463-dc6671c5-5305-4d32-9982-b44a3f62e5f4.jpg)

**Comment by m0ksem** [comment]
I think it is correct behavior. We don't support CSS named colors such as `black`, `white`, `cyan`, `purple` etc. Because it will make `vuestic-ui` extra large.

If there is unknown color, we fall back to the default `#000000` color.

In this issue, I suppose, you need to change the docs example. 
For example to `<va-checkbox color="#ff00ff" />`

Also, take a look if we have documented the things that I described above.

You can see here that we support only HEX color or string from color config.
![image](https://user-images.githubusercontent.com/23530004/128851566-cd360333-9a6c-4469-845a-ebe13bb19c23.png)
You may improve it that the end-user will understand it better.

**Comment by asvae** [comment]
We can add this information to https://vuestic.dev/en/services/colors-config.
Would you like to handle this @Derranion ?

**Comment by Derranion** [comment]
@asvae 
Alright, maybe it's better to at least add 17 W3C-standard color names to our `colorsPresets`?

It will increase project size by 0.4 KB only.

**Comment by m0ksem** [comment]
> Alright, maybe it's better to at least add 17 W3C-standard color names to our `colorsPresets`?
> 
> It will increase project size by 0.4 KB only.

@Derranion, I think it should not be in colorsPresets because users can override colors presets object.

If you really want to add standard colors, I suggest editing [ getColor ](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/services/color-config/color-config.ts#L32) method.

I will also want to use all 140 color names if there will be an option to use standard colors. But... Have you ever use these colors in your application? 🤔

**Comment by Derranion** [comment]
> @Derranion, I think it should not be in colorsPresets because users can override colors presets object.
>
> If you really want to add standard colors, I suggest editing [ getColor ](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/services/color-config/color-config.ts#L32) method.
>
@m0ksem Thanks but I thought that's what we want - to allow users to override colors if needed.

As you know [getColor](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/services/color-config/color-config.ts#L32) uses the same `colorsPresets` from global config so I'm not sure if we want to force standard colors inside the `getColor`.

Let's just briefly discuss it tomorrow.

**Comment by m0ksem** [comment]
So here we decided to allow user to use standard color names, like purple and set it's own value via colors config.

purple: '#ff0'
